--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Muqsit/ChestShop
branches:
- master
projects:
  ChestShop:
    path: ""
    libs:
      - src: muqsit/InvMenu/InvMenu
        branch: "4.0"
        version: ^4.3.8
      - src: jojoe77777/FormAPI/libFormAPI
        version: ^1.3.0
      - src: poggit/libasynql/libasynql
        version: ^4.0.1
...
