--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Muqsit/ChestShop
branches:
- master
projects:
  ChestShop:
    path: ""
    libs:
      - src: muqsit/InvMenu/InvMenu
        version: ^3.1.1
      - src: jojoe77777/FormAPI/libFormAPI
        version: 1.3.0
...
