name: ChestShop
main: muqsit\chestshop\ChestShop
api: 3.11.1
version: 4.1
commands:
  chestshop:
    aliases: ["cs", "cshop"]
permissions:
  chestshop.command.opcmd:
    default: op
  chestshop.command.add:
    default: op
  chestshop.command.remove:
    default: op
